### ISSUE TITLE
Wacky Races still not working [$228]

### ISSUE THREAD

**Issue by skmp** [reicast/gamedb#83] opened 2018-07-14 02:50 UTC
_From @SuperL2 on July 23, 2016 17:18_

I was excited to see that work was being done on Reicast again, and it seems some formerly unplayable games have become playable. However, sadly, Wacky Races still doesn't work, and I'd like to request that it be added to the queue of things to be fixed.

**Comment by SuperL2** [comment] 2018-07-16 01:03
The problem is still not solved. The picture is still mostly black. Pushing buttons will show some of the visuals, albeit glitchy, but the game is unplayable.

**Comment by SuperL2** [comment] 2018-07-25 23:50
So, I just found out that the Libretro/Retroarch version of Reicast has been updated to fix Wacky Races. However, there is no work being done on an android version of the Reicast core yet.

Could the enhancements done to the libretro core perhaps be inserted into the standalone emulator? Don't know if it can, just asking.

**Comment by skmp** [comment] 2018-07-26 22:59
Do you have the tree hash of libretro-reicast that has this issue fixed? @twinaphex probably knows more.

**Comment by SuperL2** [comment] 2018-07-26 23:20
All I know is that it was noted here: https://www.libretro.com/index.php/reicast-libretro-updates/

**Comment by twinaphex** [comment] 2018-07-26 23:46
I think it got fixed just by proxy, by backporting all of the changes over from @flyinghead that were done to the TA/PVR code.

Honestly, at this point I would just suggest backporting everything that was backported to the libretro port. The codebase can only be improved in the process; so much stuff is currently broken in upstream that it's not worth it being selective with these backports when at best there will be a 1-2fps loss in the process.

**Comment by twinaphex** [comment] 2018-07-26 23:47
There are still some parts in the menu that are not rendered properly though. Not all of the text on the billboards shows for instance in the main menu.

**Comment by SuperL2** [comment] 2018-07-27 00:00
That's still a huge improvement over what it was previous, which was no picture at all. In fact before libretro fixed it, the only emulators that rendered it playable were redream and archaic builds of demul and Makaron.

**Comment by LoungeKatt** [comment] 2018-07-27 00:05
It would make a lot more sense to attempt to pull in the changes from @flyinghead directly, since the fork is based on this source, rather than backporting a backport. That would probably avoid a few merge issues anyway.

**Comment by skmp** [comment] 2018-07-27 00:52
Also note, we can't just go ahead and pull code without an MR -- that defeats the entire purpose of having a CLA. And afair, libretro-reicast is not MIT licensed either, so....

**Comment by twinaphex** [comment] 2018-07-27 01:03
You have permission to take whatever you want from my libretro reicast repo as per your CLA. I have to be brutally honest, normally I don't like CLAs and I don't even know if I like it here, however, for the purpose of making Reicast the best open source emulator it can be, I am willing to overlook my personal misgivings on this subject and just implicitly signing this if it means we can move forward.

**Comment by LoungeKatt** [comment] 2018-07-27 01:20
The CLA would have to be approved in the PR itself (at least for the first PR / new author) and it would also have to be approved by every author included in all of the commits that equal a single PR.

**Comment by SuperL2** [comment] 2018-08-16 22:57
So, the Libretro reicast core has been ported to Android. I checked out Wacky Races.

It's the most playable it's ever been on Android. Half the screen is black, and the controls are finicky, but it's progress.

**Comment by AbandonedCart** [comment] 2018-08-16 23:44
@SuperL2 While that is great news, it isn't really relevant to this project.

**Comment by baka0815** [comment] 2018-11-03 21:02
As https://github.com/reicast/reicast-emulator/pull/1448 go merged, this is fixed.

**Closed** 2018-11-04 23:13 UTC
Labels: Bounty Granted, 🎮 wacky-races
